# Test Sentence Encoders on Apple Silicon

This notebook tests the sentence-transformers based encoders that are compatible with Apple Silicon (M1/M2/M3).

In [1]:
import os
import platform
import time

import numpy as np

# Check platform
print(f"Platform: {platform.system()}")
print(f"Machine: {platform.machine()}")
print(f"Apple Silicon: {platform.system() == 'Darwin' and platform.machine() == 'arm64'}")

Platform: Darwin
Machine: arm64
Apple Silicon: True


## 1. Test DistilUSE Encoder

Knowledge-distilled version of Universal Sentence Encoder. 512-dimensional embeddings.

In [2]:
from aymurai.models.usem import DistilUSEEncoder

distiluse = DistilUSEEncoder()
print(f"Model: {distiluse.MODEL_NAME}")
print(f"Device: {distiluse.model.device}")

[21:30:19] INFO     PyTorch version 1.12.1 available.                                                  ]8;id=14501;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/datasets/config.py\config.py]8;;\:]8;id=206166;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/datasets/config.py#54\54]8;;\

           INFO     Use pytorch device_name: mps                                         ]8;id=869653;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=10439;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#219\219]8;;\

           INFO     Load pretrained SentenceTransformer:                                 ]8;id=120097;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=328879;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#227\227]8;;\
                    sentence-transformers/distiluse-base-multilingual-cased-v2                                     

[21:30:22] INFO     Loaded                                                      ]8;id=614405;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py\sentence_transformers_encoder.py]8;;\:]8;id=742141;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py#38\38]8;;\
                    sentence-transformers/distiluse-base-multilingual-cased-v2                                     
                    on device: mps:0                                                                               

Model: sentence-transformers/distiluse-base-multilingual-cased-v2
Device: mps:0


In [3]:
# Test encoding
test_sentences = [
    "El juez dictó sentencia en el caso de violencia de género.",
    "La víctima presentó una denuncia por amenazas.",
    "Se otorgó una medida de protección a la denunciante.",
    "The judge issued a ruling in the gender violence case.",
    "The victim filed a complaint for threats.",
]

start = time.time()
embeddings_distiluse = distiluse.encode(test_sentences, encoder_type="question_encoder")
elapsed = time.time() - start

print(f"Embeddings shape: {embeddings_distiluse.shape}")
print(f"Encoding time: {elapsed:.3f}s")

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embeddings shape: (5, 512)
Encoding time: 2.070s


## 2. Test Multilingual MiniLM Encoder

Higher quality embeddings, faster inference. 384-dimensional embeddings.

In [4]:
from aymurai.models.usem import MultilingualMiniLMEncoder

minilm = MultilingualMiniLMEncoder()
print(f"Model: {minilm.MODEL_NAME}")
print(f"Device: {minilm.model.device}")

[21:30:35] INFO     Use pytorch device_name: mps                                         ]8;id=753938;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=89702;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#219\219]8;;\

           INFO     Load pretrained SentenceTransformer:                                 ]8;id=598117;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=530736;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#227\227]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[21:30:57] INFO     Loaded                                                      ]8;id=359653;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py\sentence_transformers_encoder.py]8;;\:]8;id=708994;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py#93\93]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    
                    on device: mps:0                                                                               

Model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Device: mps:0


In [5]:
start = time.time()
embeddings_minilm = minilm.encode(test_sentences, encoder_type="question_encoder")
elapsed = time.time() - start

print(f"Embeddings shape: {embeddings_minilm.shape}")
print(f"Encoding time: {elapsed:.3f}s")

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embeddings shape: (5, 384)
Encoding time: 0.661s


## 3. Test Factory Auto-Detection

In [6]:
from aymurai.models.usem import create_encoder, EncoderType

# Auto-detect (should use DistilUSE on Apple Silicon)
encoder_auto = create_encoder()
print(f"Auto-detected encoder: {type(encoder_auto).__name__}")

# Explicit selection
encoder_minilm = create_encoder(EncoderType.MINILM)
print(f"Explicit MiniLM encoder: {type(encoder_minilm).__name__}")

[21:31:05] INFO     Apple Silicon detected, using DistilUSE encoder for compatibility                 ]8;id=395517;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/factory.py\factory.py]8;;\:]8;id=43741;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/factory.py#74\74]8;;\

           INFO     Use pytorch device_name: mps                                         ]8;id=648070;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=25205;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#219\219]8;;\

           INFO     Load pretrained SentenceTransformer:                                 ]8;id=115704;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=901345;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#227\227]8;;\
                    sentence-transformers/distiluse-base-multilingual-cased-v2                                     

[21:31:08] INFO     Loaded                                                      ]8;id=827649;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py\sentence_transformers_encoder.py]8;;\:]8;id=985024;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py#38\38]8;;\
                    sentence-transformers/distiluse-base-multilingual-cased-v2                                     
                    on device: mps:0                                                                               

Auto-detected encoder: DistilUSEEncoder


           INFO     Use pytorch device_name: mps                                         ]8;id=354040;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=766574;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#219\219]8;;\

           INFO     Load pretrained SentenceTransformer:                                 ]8;id=441345;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=97549;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#227\227]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    

[21:31:12] INFO     Loaded                                                      ]8;id=644190;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py\sentence_transformers_encoder.py]8;;\:]8;id=973569;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py#93\93]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    
                    on device: mps:0                                                                               

Explicit MiniLM encoder: MultilingualMiniLMEncoder


## 4. Semantic Similarity Test

Compare similarity between Spanish and English sentences.

In [7]:
def cosine_similarity(a, b):
    """Compute cosine similarity between two vectors."""
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def similarity_matrix(embeddings, sentences):
    """Compute and display similarity matrix."""
    n = len(sentences)
    sim_matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            sim_matrix[i, j] = cosine_similarity(embeddings[i], embeddings[j])
    return sim_matrix

In [8]:
# Compute similarity matrix for DistilUSE
sim_distiluse = similarity_matrix(embeddings_distiluse, test_sentences)

print("DistilUSE Similarity Matrix:")
print("Sentences:")
for i, s in enumerate(test_sentences):
    print(f"  [{i}] {s[:60]}..." if len(s) > 60 else f"  [{i}] {s}")
print()
print(np.round(sim_distiluse, 3))

DistilUSE Similarity Matrix:
Sentences:
  [0] El juez dictó sentencia en el caso de violencia de género.
  [1] La víctima presentó una denuncia por amenazas.
  [2] Se otorgó una medida de protección a la denunciante.
  [3] The judge issued a ruling in the gender violence case.
  [4] The victim filed a complaint for threats.

[[1.    0.552 0.409 0.814 0.538]
 [0.552 1.    0.593 0.408 0.933]
 [0.409 0.593 1.    0.337 0.562]
 [0.814 0.408 0.337 1.    0.454]
 [0.538 0.933 0.562 0.454 1.   ]]


In [9]:
# Compute similarity matrix for MiniLM
sim_minilm = similarity_matrix(embeddings_minilm, test_sentences)

print("MiniLM Similarity Matrix:")
print(np.round(sim_minilm, 3))

MiniLM Similarity Matrix:
[[1.    0.399 0.489 0.645 0.3  ]
 [0.399 1.    0.539 0.236 0.922]
 [0.489 0.539 1.    0.185 0.391]
 [0.645 0.236 0.185 1.    0.213]
 [0.3   0.922 0.391 0.213 1.   ]]


## 5. Cross-lingual Similarity

Test that Spanish-English translation pairs have high similarity.

In [10]:
# Spanish sentence [0] should be similar to English sentence [3]
# Spanish sentence [1] should be similar to English sentence [4]

print("Cross-lingual similarity (Spanish ↔ English):")
print(f"\nDistilUSE:")
print(f"  '{test_sentences[0][:40]}...' ↔ '{test_sentences[3][:40]}...': {sim_distiluse[0, 3]:.3f}")
print(f"  '{test_sentences[1][:40]}...' ↔ '{test_sentences[4][:40]}...': {sim_distiluse[1, 4]:.3f}")

print(f"\nMiniLM:")
print(f"  '{test_sentences[0][:40]}...' ↔ '{test_sentences[3][:40]}...': {sim_minilm[0, 3]:.3f}")
print(f"  '{test_sentences[1][:40]}...' ↔ '{test_sentences[4][:40]}...': {sim_minilm[1, 4]:.3f}")

Cross-lingual similarity (Spanish ↔ English):

DistilUSE:
  'El juez dictó sentencia en el caso de vi...' ↔ 'The judge issued a ruling in the gender ...': 0.814
  'La víctima presentó una denuncia por ame...' ↔ 'The victim filed a complaint for threats...': 0.933

MiniLM:
  'El juez dictó sentencia en el caso de vi...' ↔ 'The judge issued a ruling in the gender ...': 0.645
  'La víctima presentó una denuncia por ame...' ↔ 'The victim filed a complaint for threats...': 0.922


## 6. Batch Encoding Performance

In [11]:
# Generate more sentences for batch test
batch_sentences = test_sentences * 100  # 500 sentences

print(f"Batch size: {len(batch_sentences)} sentences")

# DistilUSE batch
start = time.time()
batch_embeddings_distiluse = distiluse.batch_encode(batch_sentences, encoder_type="question_encoder", batch_size=64)
elapsed_distiluse = time.time() - start
print(f"\nDistilUSE batch encoding: {elapsed_distiluse:.3f}s ({len(batch_sentences)/elapsed_distiluse:.1f} sent/s)")

# MiniLM batch
start = time.time()
batch_embeddings_minilm = minilm.batch_encode(batch_sentences, encoder_type="question_encoder", batch_size=64)
elapsed_minilm = time.time() - start
print(f"MiniLM batch encoding: {elapsed_minilm:.3f}s ({len(batch_sentences)/elapsed_minilm:.1f} sent/s)")

Batch size: 500 sentences


Batches:   0%|          | 0/8 [00:00<?, ?it/s]


DistilUSE batch encoding: 2.124s (235.4 sent/s)


Batches:   0%|          | 0/8 [00:00<?, ?it/s]

MiniLM batch encoding: 1.412s (354.0 sent/s)


## 7. Environment Variable Configuration

In [12]:
# Test environment variable configuration
import importlib
import aymurai.models.usem.factory as factory_module

# Set env var and reload
os.environ["SENTENCE_ENCODER_TYPE"] = "minilm"
importlib.reload(factory_module)
from aymurai.models.usem.factory import create_encoder

encoder_from_env = create_encoder()
print(f"Encoder from SENTENCE_ENCODER_TYPE=minilm: {type(encoder_from_env).__name__}")

# Reset to auto
os.environ["SENTENCE_ENCODER_TYPE"] = "auto"

[21:31:24] INFO     Use pytorch device_name: mps                                         ]8;id=901753;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=500610;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#219\219]8;;\

           INFO     Load pretrained SentenceTransformer:                                 ]8;id=669964;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py\SentenceTransformer.py]8;;\:]8;id=805774;file:///Users/lioweltlinie/Projects/personal/backend-dev/.venv/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py#227\227]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    

[21:31:28] INFO     Loaded                                                      ]8;id=84108;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py\sentence_transformers_encoder.py]8;;\:]8;id=313130;file:///Users/lioweltlinie/Projects/personal/backend-dev/aymurai/models/usem/sentence_transformers_encoder.py#93\93]8;;\
                    sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2                                    
                    on device: mps:0                                                                               

Encoder from SENTENCE_ENCODER_TYPE=minilm: MultilingualMiniLMEncoder


## Summary

Both `DistilUSEEncoder` and `MultilingualMiniLMEncoder` work on Apple Silicon:

| Model | Embedding Dim | Speed | Quality |
|-------|---------------|-------|--------|
| DistilUSE | 512 | Good | Good (USE distillation) |
| MiniLM | 384 | Faster | Better |

Use `SENTENCE_ENCODER_TYPE=auto` for automatic platform detection.